CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_settings` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `setting` varchar(100) NOT NULL,
  `value` longtext NOT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting` (`setting`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_profiles` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `client_id` int unsigned NOT NULL,
  `type` varchar(40) NOT NULL,
  `status` varchar(30) NOT NULL,
  `verification_method` varchar(40) DEFAULT NULL,
  `real_name` varchar(191) DEFAULT NULL,
  `company_name` varchar(191) DEFAULT NULL,
  `country` char(2) DEFAULT NULL,
  `document_type` varchar(60) DEFAULT NULL,
  `id_number_hash` varchar(128) DEFAULT NULL,
  `id_number_last4` varchar(16) DEFAULT NULL,
  `phone_hash` varchar(128) DEFAULT NULL,
  `phone_last4` varchar(16) DEFAULT NULL,
  `registration_number_hash` varchar(128) DEFAULT NULL,
  `registration_number_last4` varchar(16) DEFAULT NULL,
  `data_json` longtext DEFAULT NULL,
  `rejection_reason` longtext DEFAULT NULL,
  `last_error` longtext DEFAULT NULL,
  `admin_notes` longtext DEFAULT NULL,
  `reviewed_by` int unsigned DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `client_id` (`client_id`),
  KEY `status` (`status`),
  KEY `type` (`type`),
  KEY `country` (`country`),
  KEY `document_type` (`document_type`),
  KEY `id_number_hash` (`id_number_hash`),
  KEY `phone_hash` (`phone_hash`),
  KEY `registration_number_hash` (`registration_number_hash`),
  KEY `reviewed_by` (`reviewed_by`),
  KEY `submitted_at` (`submitted_at`),
  KEY `verified_at` (`verified_at`),
  KEY `reviewed_at` (`reviewed_at`),
  KEY `expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_submissions` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `profile_id` int unsigned DEFAULT NULL,
  `client_id` int unsigned NOT NULL,
  `type` varchar(40) NOT NULL,
  `provider` varchar(80) NOT NULL,
  `status` varchar(30) NOT NULL,
  `payload_json` longtext DEFAULT NULL,
  `result_json` longtext DEFAULT NULL,
  `admin_notes` longtext DEFAULT NULL,
  `rejection_reason` longtext DEFAULT NULL,
  `reviewed_by` int unsigned DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `profile_id` (`profile_id`),
  KEY `client_id` (`client_id`),
  KEY `type` (`type`),
  KEY `provider` (`provider`),
  KEY `status` (`status`),
  KEY `reviewed_by` (`reviewed_by`),
  KEY `submitted_at` (`submitted_at`),
  KEY `reviewed_at` (`reviewed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_documents` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `profile_id` int unsigned NOT NULL,
  `submission_id` int unsigned DEFAULT NULL,
  `client_id` int unsigned NOT NULL,
  `document_type` varchar(60) NOT NULL,
  `original_name` varchar(191) NOT NULL,
  `stored_name` varchar(191) NOT NULL,
  `storage_path` varchar(500) NOT NULL,
  `file_hash` varchar(128) NOT NULL,
  `mime_type` varchar(120) DEFAULT NULL,
  `file_size` int unsigned NOT NULL,
  `status` varchar(30) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stored_name` (`stored_name`),
  KEY `profile_id` (`profile_id`),
  KEY `submission_id` (`submission_id`),
  KEY `client_id` (`client_id`),
  KEY `document_type` (`document_type`),
  KEY `file_hash` (`file_hash`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`),
  KEY `reviewed_at` (`reviewed_at`),
  KEY `deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_rules` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `scope_type` varchar(40) NOT NULL,
  `scope_value` varchar(120) NOT NULL,
  `requirement` varchar(40) NOT NULL DEFAULT 'verified',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `notes` longtext DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `scope` (`scope_type`,`scope_value`),
  KEY `scope_type` (`scope_type`),
  KEY `scope_value` (`scope_value`),
  KEY `requirement` (`requirement`),
  KEY `enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_provider_logs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `client_id` int unsigned NOT NULL,
  `provider` varchar(80) NOT NULL,
  `status` varchar(30) NOT NULL,
  `result_code` varchar(80) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `isp` varchar(80) DEFAULT NULL,
  `request_id` varchar(120) DEFAULT NULL,
  `response_json` longtext DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `provider` (`provider`),
  KEY `status` (`status`),
  KEY `result_code` (`result_code`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mod_peakrack_kyc_audit_logs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `client_id` int unsigned DEFAULT NULL,
  `order_id` int unsigned DEFAULT NULL,
  `level` varchar(20) NOT NULL,
  `message` varchar(255) NOT NULL,
  `context` longtext DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `order_id` (`order_id`),
  KEY `level` (`level`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
